version: "3"

services:
  postgresdb: 
    image: postgres
    environment: 
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: open-market
    ports: 
      - '5432:5432'